# Change these first
owner: nikko-alldata # Your GitHub organization or username, where this repository lives
repo: alldata-uptime # The name of this repository

sites:
  - name: All Data International
    url: https://alldataint.com
  - name: Showcase - All Data International
    url: https://showcase.alldataint.com
  - name: GIT - All Data International
    url: https://git.alldataint.com
  - name: Matomo - All Data International
    url: https://matomo.alldataint.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alldataint.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Status** Website ADI"
  introMessage: Status for monitoring website PT All Data International
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
